v3.0
Bug Fix: unknown uid 0 (incorrect detection of root).
Added: sd-ext backup.
Added: battery level check.
Added: SD card check.
Improved: .android_secure backup.
Fixed: various bugs and re-organized script.

diff --git a/onandroid b/onandroid
--- a/onandroid
+++ b/onandroid
@@ -1,5 +1,5 @@
 echo "##########################################"
-echo "Online Nandroid Backup v2.3"
+echo "Online Nandroid Backup v3.0"
 echo "* A tool to perform a nandroid backup"
 echo "  without booting into recovery. It can"
 echo "  be run via adb shell or terminal"
@@ -7,7 +7,8 @@ echo "  emulator in Android, thus allowing"
 echo "  you to do a live nandroid backup"
 echo "  within Android."
 echo "* This tool backups /system , /data , "
-echo "  /cache & .android_secure partitions."
+echo "  /cache , .android_secure & /sd-ext"
+echo "  partitions."
 echo "* It is fully compatible with nandroid."
 echo "* Type 'onandroid --help' for usage"
 echo "  instructions."
@@ -20,6 +21,8 @@ path="/sdcard/clockworkmod/backup"
 safety=7
 name="none"
 tz="u"
+req_power=10
+sdcard_temp_mount="/mnt/sdcard4nandroid"
 
 # Process arguments
 if [ $# -gt 0 ]; then
@@ -72,13 +75,43 @@ fi
 # Start timer
 start_time=`date +%s`
 
+# Analyse power status
+echo "`date +%T` Analysing power..."
+if [ -f /sys/class/power_supply/bq27520/capacity ]; then
+	rem_power=`cat /sys/class/power_supply/bq27520/capacity`
+	if [ `cat /sys/class/power_supply/ac/online` == "1" ]; then
+		rem_power=100
+	fi
+else
+	rem_power=100
+	echo "`date +%T` Unable to check power status! Taking a chance here..."
+fi
+
+# Check if power is sufficient
+if [ $rem_power -gt $req_power ]; then
+	echo "`date +%T` Required level of power available! Continuing..."
+else
+	echo "`date +%T` Required level of power not available! Exiting..."
+	exit 1
+fi
+
+# Check if SD card is mounted
+echo "`date +%T` Searching for SD card..."
+is_sdcard_mounted=`mount | grep "sdcard type vfat" | cut -d ' ' -f 3`
+if [ "$is_sdcard_mounted" == "" ]; then
+	echo "`date +%T` SD card not found! Exiting..."
+	exit 1
+else
+	echo "`date +%T` SD card found! Continuing..."
+fi
+
 # Check for root permissions
 echo "`date +%T` Checking for root permissions..."
-uid=`whoami`
-if [ $uid == "root" ]; then
-	echo "`date +%T` Root permissions aquired!"
+uid=`id -u`
+if [ "$uid" == "0" ]; then
+	echo "`date +%T` Root permissions aquired! Continuing..."
 else
-	echo "`date +%T` Could not aquire root permissions!"
+	echo "`date +%T` Could not aquire root permissions! Exiting..."
 	exit 1
 fi
 
@@ -86,42 +119,72 @@ fi
 echo "`date +%T` Checking for required tools..."
 mkyaffs2image=`which mkyaffs2image`
 if [ "$mkyaffs2image" == "" ]; then
-	echo "`date +%T` Error: mkyaffs2image not found in path."
+	echo "`date +%T` Error: mkyaffs2image not found in path! Exiting..."
 	exit 1
 fi
 md5sum=`which md5sum`
 if [ "$md5sum" == "" ]; then
-	echo "`date +%T` Error: md5sum not found in path."
+	echo "`date +%T` Error: md5sum not found in path! Exiting..."
 	exit 1
 fi
 tar==`which tar`
 if [ "$tar" == "" ]; then
-	echo "`date +%T` Error: tar not found in path."
+	echo "`date +%T` Error: tar not found in path! Exiting..."
 	exit 1
 fi
-echo "`date +%T` All required tools available."
+echo "`date +%T` All required tools available! Continuing..."
 
 # Disk space check (in MB)
 echo "`date +%T` Checking disk space..."
+
+# /system partition size
 entry=`df -m /system | tail -1`
 u_system=`echo $entry | cut -d' ' -f3 | cut -d'%' -f1`
+
+# /data partition size
 entry=`df -m /data | tail -1`
 u_data=`echo $entry | cut -d' ' -f3 | cut -d'%' -f1`
+
+# /cache partition size
 entry=`df -m /cache | tail -1`
 u_cache=`echo $entry | cut -d' ' -f3 | cut -d'%' -f1`
+
+# .android_secure partition size
 # Mount sdcard into a temporary location for accessing .android_secure partition
-mount -o remount rw //
-mkdir /mnt/sdcard4nandroid
-mount /dev/block/vold/179:1 /mnt/sdcard4nandroid
-cd /mnt/sdcard4nandroid
+sdcard_vold_id=`mount | grep "/mnt/sdcard type vfat" | cut -d ' ' -f 1`
+mount -o remount,rw //
+mkdir $sdcard_temp_mount
+mount $sdcard_vold_id $sdcard_temp_mount
+cd $sdcard_temp_mount
 u_as=`du -m .android_secure | cut -f1`
-req_space=`expr $u_system + $u_data + $u_cache + $u_as + $safety`
+
+# sd-ext partition size
+# Check if sd-ext is mounted
+is_sdext_mounted=`mount | grep "type ext" | cut -d ' ' -f 3`
+sdext_exists=1
+if [ "$is_sdext_mounted" == "" ]; then
+	sdext_exists=0
+fi
+if [ $sdext_exists == 1 ]; then
+	extm=`mount | grep "type ext" | cut -d ' ' -f 3`
+	entry=`df -m $extm | tail -1`
+	u_ext=`echo $entry | cut -d' ' -f3 | cut -d'%' -f1`
+else
+	u_ext=0
+fi
+
+# Required space calculation
+req_space=`expr $u_system + $u_data + $u_cache + $u_as + $u_ext + $safety`
+
+# Available space calculation
 entry=`df -m /mnt/sdcard | tail -1`
 freespace=`echo $entry | cut -d' ' -f3 | cut -d'%' -f1`
+
+# Announce available space and required space
 echo "`date +%T` SD Card Free Space: $freespace MB"
 echo "`date +%T` Required Space: $req_space MB"
 if [ $freespace -lt $req_space ]; then
-	echo "`date +%T` Not enough disk space! Exiting!"
+	echo "`date +%T` Not enough disk space! Exiting..."
 	exit 1
 else
 	echo "`date +%T` Necessary disk space available! Continuing..."
@@ -139,12 +202,12 @@ if [ ! -d $name ]; then
 		exit 1
 	fi
 else
-	echo "`date +%T` Error: $name already exists! Exiting!"
+	echo "`date +%T` Error: $name already exists! Exiting..."
 	exit 1
 fi
 touch -- $name/.nandroidwritable
 if [ ! -e $name/.nandroidwritable ]; then
-	echo "`date +%T` Error: Cannot write to $name"
+	echo "`date +%T` Error: Cannot write to $name ! Exiting..."
 	exit 1
 fi
 rm -- $name/.nandroidwritable
@@ -193,14 +256,33 @@ echo ""
 # Unmount temporary sdcard mount as .android_secure backup is complete
 # Wait 2 seconds before we umount device
 sleep 2
-umount -l /mnt/sdcard4nandroid
-cd /mnt
-rmdir sdcard4nandroid
-mount -o remount ro //
-cd $path/$name
+umount -l $sdcard_temp_mount
+rmdir $sdcard_temp_mount
+mount -o remount,ro //
+
+# Backup sd-ext
+if [ $sdext_exists == 1 ]; then
+	# Grab ext version
+	extv=`mount | grep "type ext" | cut -d ' ' -f 5`
+	# Grab mountpoint
+	extm=`mount | grep "type ext" | cut -d ' ' -f 3`
+	echo -e "`date +%T` Backing up sd-ext...\c"
+	cd $extm
+	cd ..
+	extd=`mount | grep "type ext" | cut -d ' ' -f 3 | cut -d '/' -f 2`
+	tar -cf $path/$name/sd-ext.$extv.tar $extd &
+	while [ `pidof tar` ]; do
+		echo -n "."
+		sleep 2
+	done
+	echo ""
+else
+	echo "`date +%T` sd-ext not found! Skipping backup of sd-ext!"
+fi
 
 # Generate md5
 echo -e "`date +%T` Generating md5sum...\c"
+cd $path/$name
 md5sum .android_secure.vfat.tar * > nandroid.md5 &
 while [ `pidof md5sum` ]; do
 	echo -n "."
